In [76]:
from glob import glob
import pandas as pd

adimplentes = glob('raw/adimplentes*')
inadimplentes = glob('raw/inadimplentes*')
dim = glob('raw/relat*')

In [77]:
# juntando adimplentes com concat
df = pd.DataFrame()
for file in adimplentes:
    print(file)
    df_temp = pd.read_csv(file, sep=';')
    df = pd.concat([df, df_temp])
df

raw\adimplentes_2023.csv
raw\adimplentes_2024.csv
raw\adimplentes_2025.csv

,matricula,turma,atividade,tipo_duplicata,valor,vlr_desconto,vlr_multa,vlr_juros,valor_atual,parcela,dt_vencimento,dt_pgto,vlr_pago
0,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.00,0.00,0.0,1,31/01/2023,19/01/2023,750.00
1,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.00,0.00,0.0,2,28/02/2023,24/02/2023,750.00
2,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.00,0.00,0.0,3,31/03/2023,24/03/2023,750.00
3,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.00,0.00,0.0,4,30/04/2023,24/04/2023,750.00
4,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.00,0.00,0.0,5,31/05/2023,23/05/2023,750.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,726,5º ANO - MANHÃ,NaN,SE,424.0,0.0,8.48,4.48,0.0,6,30/06/2025,04/08/2025,436.96
2050,726,5º ANO - MANHÃ,NaN,SE,424.0,0.0,8.48,4.06,0.0,7,31/07/2025,01/09/2025,436.54
2051,726,5º ANO - MANHÃ,NaN,SE,424.0,0.0,8.48,4.06,0.0,8,31/08/2025,30/09/2025,436.54
2052,726,5º ANO - MANHÃ,NaN,SE,424.0,0.0,8.48,4.34,0.0,9,30/09/2025,03/11/2025,436.82
2053,726,5º ANO - MANHÃ,NaN,SE,424.0,0.0,8.48,6.86,0.0,10,31/10/2025,22/12/2025,439.34

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6432 entries, 0 to 2053
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   matricula       6432 non-null   int64
 1   turma           6432 non-null   object
 2   atividade       0 non-null      float64
 3   tipo_duplicata  6432 non-null   object
 4   valor           6432 non-null   float64
 5   vlr_desconto    6432 non-null   float64
 6   vlr_multa       6432 non-null   float64
 7   vlr_juros       6432 non-null   float64
 8   valor_atual     6432 non-null   float64
 9   parcela         6432 non-null   int64
 10  dt_vencimento   6432 non-null   object
 11  dt_pgto         6432 non-null   object
 12  vlr_pago        6432 non-null   float64
dtypes: float64(7), int64(2), object(4)
memory usage: 703.5+ KB

In [79]:
df['dt_vencimento'] = pd.to_datetime(df['dt_vencimento'])
df['dt_pgto'] = pd.to_datetime(df['dt_pgto'])

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16432\53809512.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['dt_vencimento'] = pd.to_datetime(df['dt_vencimento'])
C:\Users\Usuario\AppData\Local\Temp\ipykernel_16432\53809512.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['dt_pgto'] = pd.to_datetime(df['dt_pgto'])

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6432 entries, 0 to 2053
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   matricula       6432 non-null   int64
 1   turma           6432 non-null   object
 2   atividade       0 non-null      float64
 3   tipo_duplicata  6432 non-null   object
 4   valor           6432 non-null   float64
 5   vlr_desconto    6432 non-null   float64
 6   vlr_multa       6432 non-null   float64
 7   vlr_juros       6432 non-null   float64
 8   valor_atual     6432 non-null   float64
 9   parcela         6432 non-null   int64
 10  dt_vencimento   6432 non-null   datetime64[ns]
 11  dt_pgto         6432 non-null   datetime64[ns]
 12  vlr_pago        6432 non-null   float64
dtypes: datetime64[ns](2), float64(7), int64(2), object(2)
memory usage: 703.5+ KB

In [81]:
df = df.sort_values(by='dt_vencimento').reset_index(drop=True)
data_min = df['dt_pgto'].min()
data_max = df['dt_pgto'].max()
df

,matricula,turma,atividade,tipo_duplicata,valor,vlr_desconto,vlr_multa,vlr_juros,valor_atual,parcela,dt_vencimento,dt_pgto,vlr_pago
0,894,INFANTIL II A - MANHÃ,NaN,SE,894.0,0.0,0.0,0.0,0.0,1,2023-01-31,2023-01-19,750.00
1,505,4º ANO - MANHÃ,NaN,SE,483.0,0.0,0.0,0.0,0.0,1,2023-01-31,2022-12-12,300.00
2,840,INFANTIL IV B - TARDE,NaN,SE,333.0,0.0,0.0,0.0,0.0,1,2023-01-31,2022-12-06,280.00
3,666,INFANTIL V B - TARDE,NaN,SE,333.0,0.0,0.0,0.0,0.0,1,2023-01-31,2022-12-15,280.00
4,872,INFANTIL V B - TARDE,NaN,SE,333.0,0.0,0.0,0.0,0.0,1,2023-01-31,2022-12-16,333.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6427,495,5º ANO - MANHÃ,NaN,SE,424.0,0.0,0.0,0.0,0.0,12,2025-12-31,2025-12-23,318.00
6428,921,1° ANO C - TARDE,NaN,SE,514.0,0.0,0.0,0.0,0.0,12,2025-12-31,2025-12-30,471.59
6429,685,2º ANO - MANHÃ,NaN,SE,424.0,0.0,0.0,0.0,0.0,12,2025-12-31,2025-12-16,381.60
6430,1036,3º ANO - MANHÃ,NaN,SE,1100.0,0.0,0.0,0.0,0.0,12,2025-12-31,2025-12-24,899.91
6431,946,INFANTIL IV B - TARDE,NaN,SE,496.0,0.0,0.0,0.0,0.0,12,2025-12-31,2025-12-29,476.16

In [82]:
df.to_parquet('processed/fato_adimplentes.parquet', engine='pyarrow')

In [83]:
# juntando inadimplentes com concat
df = pd.DataFrame()
for file in inadimplentes:
    print(file)
    df_temp = pd.read_csv(file, sep=';')
    df = pd.concat([df, df_temp])
df['dt_vencimento'] = pd.to_datetime(df['dt_vencimento'])
df = df.sort_values(by='dt_vencimento').reset_index(drop=True)
df.to_parquet('processed/fato_inadimplentes.parquet', engine='pyarrow')

raw\inadimplentes_2023.csv
raw\inadimplentes_2024.csv
raw\inadimplentes_2025.csv

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16432\516236260.py:7: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['dt_vencimento'] = pd.to_datetime(df['dt_vencimento'])

In [84]:
# gerando dimensões
df = pd.read_csv(dim[0], sep=';')
df.head()

,aluno,matricula,turma,atividade,tipo_duplicata,responsavel,telefone1,telefone2,telefone_resp1,telefone_resp2,...,vlr_desconto,vlr_multa,vlr_juros,valor_atual,parcela,dt_vencimento,rcpf,rendereco,rendereco1,rendereco2
0,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,...,0.0,0.0,0.0,0.0,1,31/01/2024,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
1,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,...,0.0,0.0,0.0,0.0,2,29/02/2024,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
2,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,...,0.0,0.0,0.0,0.0,3,01/04/2024,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
3,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,...,0.0,0.0,0.0,0.0,4,30/04/2024,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
4,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,...,0.0,0.0,0.0,0.0,5,31/05/2024,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova

In [85]:
df.columns

Index(['aluno', 'matricula', 'turma', 'atividade', 'tipo_duplicata',
       'responsavel', 'telefone1', 'telefone2', 'telefone_resp1',
       'telefone_resp2', 'valor', 'vlr_desconto', 'vlr_multa', 'vlr_juros',
       'valor_atual', 'parcela', 'dt_vencimento', 'rcpf', 'rendereco',
       'rendereco1', 'rendereco2'],
      dtype='object')

In [86]:
df = df.drop(columns=['valor', 'vlr_desconto', 'vlr_multa', 'vlr_juros', 'valor_atual', 'parcela', 'dt_vencimento'])
df.head()

,aluno,matricula,turma,atividade,tipo_duplicata,responsavel,telefone1,telefone2,telefone_resp1,telefone_resp2,rcpf,rendereco,rendereco1,rendereco2
0,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
1,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
2,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
3,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova
4,ANTHONY GABRIEL BARBOSA DA SILVA,945,INFANTIL II A - MANHÃ,NaN,SE,ANDRESSA CARLA LIMA DA SILVA,(83) 98153-5384,(83) 98743-2161,(83) 98153-5384,(83) 98743-2161,717.615.834-76,"58304-500 Rua: Santa Verônica número, 61 - Vár...","Rua: Santa Verônica número, 61",58304-500 Várzea Nova

In [87]:
df = df.drop_duplicates(subset=['matricula'], keep='first')

In [88]:
df = df.sort_values('matricula').reset_index(drop=True)
df

,aluno,matricula,turma,atividade,tipo_duplicata,responsavel,telefone1,telefone2,telefone_resp1,telefone_resp2,rcpf,rendereco,rendereco1,rendereco2
0,KAIO MIGUEL DIAS LORDÃO,85,5º ANO - MANHÃ,NaN,SE,NADJA MARIA DIAS DOS SANTOS LORDÃO,(83)3224-7371,(83)9868-08869,(83)3218-9313,(83)9881-40393,036.197.684-47,"58025-330 RUA JOSÉ MESQUITA, 251 - JARDIM 13 D...","RUA JOSÉ MESQUITA, 251",58025-330 JARDIM 13 DE MAIO
1,VICTOR LUCCA FRAGOSO DE OLIVEIRA,92,5º ANO - MANHÃ,NaN,SE,GRACYELLE ALVES FRAGOSO,(83) 98843-5292,(83)9883-77553,NaN,(83)9883-77553,045.019.144-32,58025-130 RUA PROFESOR INÁCIO SERRANO DE ANDRA...,"RUA PROFESOR INÁCIO SERRANO DE ANDRADE, 2",58025-130 TREZE DE MAIO
2,MIGUEL BELTRÃO DO NASCIMENTO,114,5º ANO - MANHÃ,NaN,SE,MARCOS FERNANDES BELTRÃO,NaN,(83) 98782-6114,NaN,(83) 98782-6114,338.651.164-34,"58010-660 RUA AUGUSTO SIMÕES, 189 - VARADOURO","RUA AUGUSTO SIMÕES, 189",58010-660 VARADOURO
3,MARIANA SILVA NASCIMENTO,132,4º ANO - MANHÃ,NaN,SE,EDRINA DOS SANTOS SILVA JUSTINO DO NASCIMENTO,(83)9992-80122,(83)9873-46801,(83) 3208-3100,(83)9873-46801,569.130.444-53,"58015-140 RUA CAPITÃO OTÁVIO FERREIRA MACHADO,...","RUA CAPITÃO OTÁVIO FERREIRA MACHADO, 30",58015-140 JAGUARIBE
4,SAFIRA QUEIROZ RAMOS,338,5º ANO - TARDE,NaN,SE,STÉFANE ALMEIDA QUEIROZ ARAÚJO RAMOS,NaN,(83)9881-22911,NaN,(83)9883-80102,066.276.264-97,"58020-840 RUA LUIZ OLIVEIRA DA SILVA, 81 - TAMBIÁ","RUA LUIZ OLIVEIRA DA SILVA, 81",58020-840 TAMBIÁ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,LAURA ELIS COSTA DE SOUZA,989,INFANTIL III B - TARDE,NaN,SE,KATIA DA SILVA COSTA DE SOUZA,(83) 98867-8348,(83) 98604-6164,NaN,(83) 98867-8348,088.724.134-43,58020-347 Rua Fotógrafo Ernani Augusto de Carv...,"Rua Fotógrafo Ernani Augusto de Carvalho, 77",58020-347 Roger
192,PEDRO ENRICO COSTA DA SILVA,990,INFANTIL IV B - TARDE,NaN,SE,KATIA DA SILVA COSTA DE SOUZA,(83) 98867-8348,(83) 98604-6164,NaN,(83) 98867-8348,088.724.134-43,58020-347 Rua Fotógrafo Ernani Augusto de Carv...,"Rua Fotógrafo Ernani Augusto de Carvalho, 77",58020-347 Roger
193,ISADORA GALIZA BRITO DE CARVALHO,991,INFANTIL II A - MANHÃ,NaN,SE,PEDRO BATISTA DE CARVALHO FILHO,(83) 98778-6745,(83) 98725-0006,NaN,(98)7250-006,054.549.884-80,58020-670 AVENIDA DESEMBARGADOR BOTO DE MENEZE...,"AVENIDA DESEMBARGADOR BOTO DE MENEZES, 0",58020-670 TAMBIÁ
194,BIANCA MACIEL FERREIRA,992,3º ANO - TARDE,NaN,SE,LIDIANE DE VASCONCELLOS MACIEL,(83) 98846-0708,(83) 98865-5795,NaN,(83) 98846-0708,970.375.080-04,"58020-670 Rua Desembargador Boto de Menezes, 9...","Rua Desembargador Boto de Menezes, 99",58020-670 Tambiá
195,MARINA MENDES COSTA DE MORAIS,993,INFANTIL II A - MANHÃ,NaN,SE,PALLOMA VITÓRIA COSTA MENDES,(83) 99695-6290,(83) 99995-3022,NaN,(83) 99695-6290,127.994.744-62,"58036-190 Rua Antônio de Oliveira Moura, 345 -...","Rua Antônio de Oliveira Moura, 345",58036-190 Aeroclube

In [89]:
df.to_parquet('processed/dim_matricula.parquet', engine='pyarrow')

In [93]:
d_calendario = pd.DataFrame({'data': pd.date_range(data_min, data_max)})
d_calendario['ano'] = d_calendario['data'].dt.year
d_calendario['mes_num'] = d_calendario['data'].dt.month
d_calendario['mes_nome'] = d_calendario['data'].dt.month_name()
d_calendario['trimestre'] = d_calendario['data'].dt.quarter
d_calendario['dia_semana'] = d_calendario['data'].dt.day_name()
d_calendario['mes_ano_ref'] = d_calendario['data'].dt.strftime('%Y-%m')

In [94]:
d_calendario

           data   ano  mes_num  mes_nome  trimestre dia_semana mes_ano_ref
0    2022-10-27  2022       10   October          4   Thursday     2022-10
1    2022-10-28  2022       10   October          4     Friday     2022-10
2    2022-10-29  2022       10   October          4   Saturday     2022-10
3    2022-10-30  2022       10   October          4     Sunday     2022-10
4    2022-10-31  2022       10   October          4     Monday     2022-10
...         ...   ...      ...       ...        ...        ...         ...
1197 2026-02-05  2026        2  February          1   Thursday     2026-02
1198 2026-02-06  2026        2  February          1     Friday     2026-02
1199 2026-02-07  2026        2  February          1   Saturday     2026-02
1200 2026-02-08  2026        2  February          1     Sunday     2026-02
1201 2026-02-09  2026        2  February          1     Monday     2026-02

[1202 rows x 7 columns]

In [96]:
import numpy as np
# Extrai o ano como string
ano = d_calendario['data'].dt.year.astype(str)

# Define o semestre: .1 se mês <= 6, senão .2
d_calendario['periodo_letivo'] = ano + np.where(d_calendario['data'].dt.month <= 6, '.1', '.2')

In [97]:
d_calendario

,data,ano,mes_num,mes_nome,trimestre,dia_semana,mes_ano_ref,periodo_letivo
0,2022-10-27,2022,10,October,4,Thursday,2022-10,2022.2
1,2022-10-28,2022,10,October,4,Friday,2022-10,2022.2
2,2022-10-29,2022,10,October,4,Saturday,2022-10,2022.2
3,2022-10-30,2022,10,October,4,Sunday,2022-10,2022.2
4,2022-10-31,2022,10,October,4,Monday,2022-10,2022.2
...,...,...,...,...,...,...,...,...
1197,2026-02-05,2026,2,February,1,Thursday,2026-02,2026.1
1198,2026-02-06,2026,2,February,1,Friday,2026-02,2026.1
1199,2026-02-07,2026,2,February,1,Saturday,2026-02,2026.1
1200,2026-02-08,2026,2,February,1,Sunday,2026-02,2026.1
1201,2026-02-09,2026,2,February,1,Monday,2026-02,2026.1

In [98]:
d_calendario.to_parquet('processed/dim_calendario.parquet', engine='pyarrow')